@baseUrl = http://localhost:8080/api

### Creates a new Player
POST {{baseUrl}}/players

### Seats a Player on a given Table

@tableId = 7c22fac2-3224-41c9-b277-cdaf9aa32316sdfs

POST {{baseUrl}}/players?table={{tableId}}
