@baseUrl = http://localhost:8080/api

### Creates a new Player
POST {{baseUrl}}/players

### Seats a Player on a given Table

@tableId = 5642e020-7d95-4fea-8acc-a6ceb6344e47sdfd

POST {{baseUrl}}/players?table={{tableId}}
